<a href="https://colab.research.google.com/github/clovesrocha/MiniCursoIP/blob/master/matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Criando uma matriz
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acessando elementos da matriz
elemento = matriz[0, 1]  # Obtém o elemento na linha 0 e coluna 1 (valor 2)

# Obtendo o número de linhas e colunas
num_linhas = matriz.shape[0]  # Retorna o número de linhas (3)
num_colunas = matriz.shape[1]  # Retorna o número de colunas (3)

# Iterando sobre elementos da matriz
for linha in matriz:
    for elemento in linha:
        print(elemento)

# Operações matriciais
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

soma = matriz1 + matriz2  # Soma de matrizes
produto = np.dot(matriz1, matriz2)  # Produto de matrizes

# Transposição de matriz
matriz_transposta = matriz.T

# Indexação booleana
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
condicao = matriz > 5  # Cria uma matriz de booleanos baseada na condição
elementos_maiores_que_5 = matriz[condicao]  # Obtém elementos maiores que 5

# Outras operações úteis incluem: média, mínimo, máximo, etc.
media = np.mean(matriz)
valor_minimo = np.min(matriz)
valor_maximo = np.max(matriz)

print(matriz)


1
2
3
4
5
6
7
8
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
